--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/harsh/Pictures/Wallpapers/walls/gruvbox/ThingiesCafe.jpg"

-- Special
background="#101212"
foreground="#c3c3c3"
cursor="#c3c3c3"

-- Colors
color0="#101212"
color1="#6E6357"
color2="#8D7660"
color3="#CB7B4E"
color4="#7C8366"
color5="#A69369"
color6="#CAAC6E"
color7="#c3c3c3"
color8="#596d6d"
color9="#6E6357"
color10="#8D7660"
color11="#CB7B4E"
color12="#7C8366"
color13="#A69369"
color14="#CAAC6E"
color15="#c3c3c3"
