--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/harsh/Downloads/wall/gruv-material.png"

-- Special
background="#0f0f10"
foreground="#c3c3c3"
cursor="#c3c3c3"

-- Colors
color0="#0f0f10"
color1="#69847C"
color2="#868B7A"
color3="#759C92"
color4="#7DAEA3"
color5="#A3AA92"
color6="#81B5AA"
color7="#c3c3c3"
color8="#6c5959"
color9="#69847C"
color10="#868B7A"
color11="#759C92"
color12="#7DAEA3"
color13="#A3AA92"
color14="#81B5AA"
color15="#c3c3c3"
