[colors.primary]
background = "#0f0f10"
foreground = "#c3c3c3"

[colors.cursor]
text = "#0f0f10"
cursor = "#c3c3c3"

[colors.vi_mode_cursor]
text = "#0f0f10"
cursor = "#c3c3c3"

[colors.search.matches]
foreground = "#0f0f10"
background = "#c3c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6c5959"
background = "#c3c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f0f10"
red = "#69847C"
green = "#868B7A"
yellow = "#759C92"
blue = "#7DAEA3"
magenta = "#A3AA92"
cyan = "#81B5AA"
white = "#c3c3c3"

[colors.bright]
black = "#6c5959"
red = "#69847C"
green = "#868B7A"
yellow = "#759C92"
blue = "#7DAEA3"
magenta = "#A3AA92"
cyan = "#81B5AA"
white = "#c3c3c3"

[colors.dim]
black = "#c3c3c3"
red = "#69847C"
green = "#A3AA92"
yellow = "#759C92"
blue = "#7DAEA3"
magenta = "#868B7A"
cyan = "#81B5AA"
white = "#6c5959"

