# Shell variables
# Generated by 'wal'
wallpaper="/home/harsh/Pictures/Wallpapers/gruvbox_room.png"

# Special
background='#101213'
foreground='#c3c3c4'
cursor='#c3c3c4'

# Colors
color0='#101213'
color1='#676D64'
color2='#86786C'
color3='#63827D'
color4='#958977'
color5='#3C8186'
color6='#568D8B'
color7='#c3c3c4'
color8='#59636e'
color9='#676D64'
color10='#86786C'
color11='#63827D'
color12='#958977'
color13='#3C8186'
color14='#568D8B'
color15='#c3c3c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
