# Shell variables
# Generated by 'wal'
wallpaper="/home/harsh/Downloads/wall/gruv-material.png"

# Special
background='#0f0f10'
foreground='#c3c3c3'
cursor='#c3c3c3'

# Colors
color0='#0f0f10'
color1='#69847C'
color2='#868B7A'
color3='#759C92'
color4='#7DAEA3'
color5='#A3AA92'
color6='#81B5AA'
color7='#c3c3c3'
color8='#6c5959'
color9='#69847C'
color10='#868B7A'
color11='#759C92'
color12='#7DAEA3'
color13='#A3AA92'
color14='#81B5AA'
color15='#c3c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
