# Shell variables
# Generated by 'wal'
wallpaper="/home/harsh/Pictures/Wallpapers/walls/gruvbox/ThingiesCafe.jpg"

# Special
background='#101212'
foreground='#c3c3c3'
cursor='#c3c3c3'

# Colors
color0='#101212'
color1='#6E6357'
color2='#8D7660'
color3='#CB7B4E'
color4='#7C8366'
color5='#A69369'
color6='#CAAC6E'
color7='#c3c3c3'
color8='#596d6d'
color9='#6E6357'
color10='#8D7660'
color11='#CB7B4E'
color12='#7C8366'
color13='#A69369'
color14='#CAAC6E'
color15='#c3c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
