--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/harsh/Pictures/Wallpapers/field.jpeg"

-- Special
background="#0b070c"
foreground="#dbacbe"
cursor="#dbacbe"

-- Colors
color0="#0b070c"
color1="#E8974C"
color2="#3E6D93"
color3="#676B95"
color4="#726E94"
color5="#9D658C"
color6="#8E6A91"
color7="#dbacbe"
color8="#997885"
color9="#E8974C"
color10="#3E6D93"
color11="#676B95"
color12="#726E94"
color13="#9D658C"
color14="#8E6A91"
color15="#dbacbe"
